# Generated by Django 4.2.11 on 2024-03-25 13:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eatery', '0005_alter_booking_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('user', 'date', 'time', 'menu', 'table_choice')},
        ),
    ]
